/*
 * Copyright 2015 Olivier Grégoire <fror@users.noreply.github.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package be.fror.password.rule;

/**
 * A rule specifically designed to validate or generate passwords according to the characters they
 * contain.
 *
 * <p>
 * If passwords must be generated by <tt>Ruler</tt>, only rules implementing this class will be
 * used.
 *
 * @author Olivier Grégoire &lt;fror@users.noreply.github.com&gt;
 */
public interface CharacterRule extends Rule {

  /**
   * Returns the valid characters for this rule as a <tt>String</tt>.
   *
   * <p>
   * This method may not return <tt>null</tt> or the empty string (<tt>""</tt>) or the result of
   * calls using this rule will be non-predictible.
   *
   * @return the valid characters for this rule as a <tt>String</tt>.
   */
  public String getValidCharacters();

  /**
   * Returns the number of character that this rule must match to validate or generate a password.
   *
   * @return the number of character that this rule must match to validate or generate a password.
   */
  public int getNumberOfCharacters();

}
